defaults:
  params:
    # Following parameters are used in Coq CircleCI Job (using yaml
    # reference syntax)
    working_directory: &workdir ~/coq
    base_image: &base opam:ubuntu-16.04_ocaml-4.05.0_flambda

  # Job configuration
  config: &coq
    working_directory: *workdir
    docker:
      - image: *base

version: 2

# Defines individual jobs, see the workflows section below for job orchestration
jobs:
  # TODO: linter

  # Build and prepare test environment
  build:
    <<: *coq
    steps:
      - checkout
      - run:
          name: Install system dependencies for build
          command: |
            apt-get update && apt-get install -y
              aspcud \
              libgtk2.0-dev \
              libgtksourceview2.0-dev \
              texlive-latex-base \
              texlive-latex-recommended \
              texlive-latex-extra \
              texlive-math-extra \
              texlive-fonts-recommended \
              texlive-fonts-extra \
              latex-xcolor \
              ghostscript \
              transfig \
              imagemagick \
              tipa
      # Restore last version of the dependencies in cache When a new
      # major version of caches has to be generated, please use
      # vYYMMDD format to avoid collision.
      - restore_cache:
          key: coq-opam-cache-{{ arch }}-v171208-
      - run:
      - run:
          name: Build opam dependencies
          command: |
            opam install -y camlp5 ocamlfind hevea lablgtk lablgtk-extras
      - save_cache:
          key: coq-opam-cache-{{ arch }}-v171208-static-deps
          paths:
            - ~/.opam
      - run:
          name: Configure
          command: ./configure -local
      - run:
          name: Build -j2
          command: make
      - run:
          name: Validate
          command: make -j2 validate
      - persist_to_workspace:
          root: &workspace ~/
          paths:
            - .opam
            - coq/

  bignums:
    <<: *coq
    steps:
      # Restore workspace
      - checkout
      - attach_workspace:
          at: *workspace
      - run:
          name: Build
          command: make -j2 TIMED=1 ci-bignums
      # bignums is a dependency
      - persist_to_workspace:
          root: &workspace ~/
          paths:
            - coq/

  color:
    <<: *coq
    steps:
      # Restore workspace
      - checkout
      - attach_workspace:
          at: *workspace
      - run:
          name: Build
          command: make -j2 TIMED=1 ci-color

  compcert:
    <<: *coq
    steps:
      # Restore workspace
      - checkout
      - attach_workspace:
          at: *workspace
      - run:
          name: Build
          command: make -j2 TIMED=1 ci-compcert

workflows:
  version: 2
  # Run on each push
  ci:
    jobs:
      - build
      - bignums:
        requires:
        - build
      - color:
        requires:
        - build
        - bignums
      - compcert:
        requires:
        - build
